### ISSUE TITLE
[User Feedback] Initial user testing

### ISSUE THREAD

**Issue by galenseilis** [AmrDeveloper/PyQL#3]
I was able to install the crate using cargo, and then added `pyql` to my environmental variables.

I ran `pyql -f core.py`  (see [core.py](https://github.com/galenseilis/DESimpy/blob/main/src/desimpy/core.py) for more info) and it seemed to list all of the functions accurately. I did not count the number of arguments carefully, but skimming through the `argument_count` and `function` that seems to be correct.

I tried all the commands on the README for this project and they seemed to produce the correct behaviour.

Only some basic function info is available but this is looking really promising.

No action items. Feel free to close after reading.

**Comment by AmrDeveloper** [comment]
Thanks for feed back @galenseilis,

The idea here is that function type is a user defined type that point to PythonFunctionStatement node, that mean we can perform analysis queries like is this function has assert, meltable return ...etc, i am working on the design now :D

**Comment by galenseilis** [comment]
> Thanks for feed back @galenseilis,
> 
> The idea here is that function type is a user defined type that point to PythonFunctionStatement node, that mean we can perform analysis queries like is this function has assert, meltable return ...etc, i am working on the design now :D

That's exciting! Yeah, further ability to inspect the properties of the functions would be an asset!
